version: '3.8'

services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile.backend
    container_name: status-backend
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3601
    ports:
      - "3601:3601"
    # Add user mapping to match container's app_user
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3601/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: status-frontend
    ports:
      - "3600:80"
    environment:
      - VITE_API_URL=https://status-api.joseserver.com
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: status-network