version: '3.8'

services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile.backend
    volumes:
      - ./src:/app/src
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./src/frontend
      target: build
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"