version: '3.8'

services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile.backend
    container_name: status-backend
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: status-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: status-network